CREATE DATABASE projetweb;
USE projetweb;

 CREATE TABLE users (
  id INTEGER PRIMARY KEY,
  pseudo VARCHAR(255) UNIQUE NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  address VARCHAR(255) NOT NULL, 
  phone_number VARCHAR(15) UNIQUE NOT NULL,
  created DATETIME
);
